#[macro_use] mod _common;
pub use self::_common::*;



pub use self::object::Object;
pub use self::function::{Function, RTDFunctionType};
pub use self::account_ttl::AccountTtl;
pub use self::address::Address;
pub use self::animation::Animation;
pub use self::animations::Animations;
pub use self::audio::Audio;
pub use self::authentication_code_info::AuthenticationCodeInfo;
pub use self::authentication_code_type::{AuthenticationCodeType, RTDAuthenticationCodeTypeType};
pub use self::authentication_code_type_telegram_message::AuthenticationCodeTypeTelegramMessage;
pub use self::authentication_code_type_sms::AuthenticationCodeTypeSms;
pub use self::authentication_code_type_call::AuthenticationCodeTypeCall;
pub use self::authentication_code_type_flash_call::AuthenticationCodeTypeFlashCall;
pub use self::authorization_state::{AuthorizationState, RTDAuthorizationStateType};
pub use self::authorization_state_wait_tdlib_parameters::AuthorizationStateWaitTdlibParameters;
pub use self::authorization_state_wait_encryption_key::AuthorizationStateWaitEncryptionKey;
pub use self::authorization_state_wait_phone_number::AuthorizationStateWaitPhoneNumber;
pub use self::authorization_state_wait_code::AuthorizationStateWaitCode;
pub use self::authorization_state_wait_password::AuthorizationStateWaitPassword;
pub use self::authorization_state_ready::AuthorizationStateReady;
pub use self::authorization_state_logging_out::AuthorizationStateLoggingOut;
pub use self::authorization_state_closing::AuthorizationStateClosing;
pub use self::authorization_state_closed::AuthorizationStateClosed;
pub use self::basic_group::BasicGroup;
pub use self::basic_group_full_info::BasicGroupFullInfo;
pub use self::bot_command::BotCommand;
pub use self::bot_info::BotInfo;
pub use self::call::Call;
pub use self::call_connection::CallConnection;
pub use self::call_discard_reason::{CallDiscardReason, RTDCallDiscardReasonType};
pub use self::call_discard_reason_empty::CallDiscardReasonEmpty;
pub use self::call_discard_reason_missed::CallDiscardReasonMissed;
pub use self::call_discard_reason_declined::CallDiscardReasonDeclined;
pub use self::call_discard_reason_disconnected::CallDiscardReasonDisconnected;
pub use self::call_discard_reason_hung_up::CallDiscardReasonHungUp;
pub use self::call_id::CallId;
pub use self::call_protocol::CallProtocol;
pub use self::call_state::{CallState, RTDCallStateType};
pub use self::call_state_pending::CallStatePending;
pub use self::call_state_exchanging_keys::CallStateExchangingKeys;
pub use self::call_state_ready::CallStateReady;
pub use self::call_state_hanging_up::CallStateHangingUp;
pub use self::call_state_discarded::CallStateDiscarded;
pub use self::call_state_error::CallStateError;
pub use self::callback_query_answer::CallbackQueryAnswer;
pub use self::callback_query_payload::{CallbackQueryPayload, RTDCallbackQueryPayloadType};
pub use self::callback_query_payload_data::CallbackQueryPayloadData;
pub use self::callback_query_payload_game::CallbackQueryPayloadGame;
pub use self::chat::Chat;
pub use self::chat_action::{ChatAction, RTDChatActionType};
pub use self::chat_action_typing::ChatActionTyping;
pub use self::chat_action_recording_video::ChatActionRecordingVideo;
pub use self::chat_action_uploading_video::ChatActionUploadingVideo;
pub use self::chat_action_recording_voice_note::ChatActionRecordingVoiceNote;
pub use self::chat_action_uploading_voice_note::ChatActionUploadingVoiceNote;
pub use self::chat_action_uploading_photo::ChatActionUploadingPhoto;
pub use self::chat_action_uploading_document::ChatActionUploadingDocument;
pub use self::chat_action_choosing_location::ChatActionChoosingLocation;
pub use self::chat_action_choosing_contact::ChatActionChoosingContact;
pub use self::chat_action_start_playing_game::ChatActionStartPlayingGame;
pub use self::chat_action_recording_video_note::ChatActionRecordingVideoNote;
pub use self::chat_action_uploading_video_note::ChatActionUploadingVideoNote;
pub use self::chat_action_cancel::ChatActionCancel;
pub use self::chat_event::ChatEvent;
pub use self::chat_event_action::{ChatEventAction, RTDChatEventActionType};
pub use self::chat_event_message_edited::ChatEventMessageEdited;
pub use self::chat_event_message_deleted::ChatEventMessageDeleted;
pub use self::chat_event_message_pinned::ChatEventMessagePinned;
pub use self::chat_event_message_unpinned::ChatEventMessageUnpinned;
pub use self::chat_event_member_joined::ChatEventMemberJoined;
pub use self::chat_event_member_left::ChatEventMemberLeft;
pub use self::chat_event_member_invited::ChatEventMemberInvited;
pub use self::chat_event_member_promoted::ChatEventMemberPromoted;
pub use self::chat_event_member_restricted::ChatEventMemberRestricted;
pub use self::chat_event_title_changed::ChatEventTitleChanged;
pub use self::chat_event_description_changed::ChatEventDescriptionChanged;
pub use self::chat_event_username_changed::ChatEventUsernameChanged;
pub use self::chat_event_photo_changed::ChatEventPhotoChanged;
pub use self::chat_event_invites_toggled::ChatEventInvitesToggled;
pub use self::chat_event_sign_messages_toggled::ChatEventSignMessagesToggled;
pub use self::chat_event_sticker_set_changed::ChatEventStickerSetChanged;
pub use self::chat_event_is_all_history_available_toggled::ChatEventIsAllHistoryAvailableToggled;
pub use self::chat_event_log_filters::ChatEventLogFilters;
pub use self::chat_events::ChatEvents;
pub use self::chat_invite_link::ChatInviteLink;
pub use self::chat_invite_link_info::ChatInviteLinkInfo;
pub use self::chat_member::ChatMember;
pub use self::chat_member_status::{ChatMemberStatus, RTDChatMemberStatusType};
pub use self::chat_member_status_creator::ChatMemberStatusCreator;
pub use self::chat_member_status_administrator::ChatMemberStatusAdministrator;
pub use self::chat_member_status_member::ChatMemberStatusMember;
pub use self::chat_member_status_restricted::ChatMemberStatusRestricted;
pub use self::chat_member_status_left::ChatMemberStatusLeft;
pub use self::chat_member_status_banned::ChatMemberStatusBanned;
pub use self::chat_members::ChatMembers;
pub use self::chat_members_filter::{ChatMembersFilter, RTDChatMembersFilterType};
pub use self::chat_members_filter_administrators::ChatMembersFilterAdministrators;
pub use self::chat_members_filter_members::ChatMembersFilterMembers;
pub use self::chat_members_filter_restricted::ChatMembersFilterRestricted;
pub use self::chat_members_filter_banned::ChatMembersFilterBanned;
pub use self::chat_members_filter_bots::ChatMembersFilterBots;
pub use self::chat_notification_settings::ChatNotificationSettings;
pub use self::chat_photo::ChatPhoto;
pub use self::chat_report_reason::{ChatReportReason, RTDChatReportReasonType};
pub use self::chat_report_reason_spam::ChatReportReasonSpam;
pub use self::chat_report_reason_violence::ChatReportReasonViolence;
pub use self::chat_report_reason_pornography::ChatReportReasonPornography;
pub use self::chat_report_reason_child_abuse::ChatReportReasonChildAbuse;
pub use self::chat_report_reason_copyright::ChatReportReasonCopyright;
pub use self::chat_report_reason_custom::ChatReportReasonCustom;
pub use self::chat_report_spam_state::ChatReportSpamState;
pub use self::chat_type::{ChatType, RTDChatTypeType};
pub use self::chat_type_private::ChatTypePrivate;
pub use self::chat_type_basic_group::ChatTypeBasicGroup;
pub use self::chat_type_supergroup::ChatTypeSupergroup;
pub use self::chat_type_secret::ChatTypeSecret;
pub use self::chats::Chats;
pub use self::check_chat_username_result::{CheckChatUsernameResult, RTDCheckChatUsernameResultType};
pub use self::check_chat_username_result_ok::CheckChatUsernameResultOk;
pub use self::check_chat_username_result_username_invalid::CheckChatUsernameResultUsernameInvalid;
pub use self::check_chat_username_result_username_occupied::CheckChatUsernameResultUsernameOccupied;
pub use self::check_chat_username_result_public_chats_too_much::CheckChatUsernameResultPublicChatsTooMuch;
pub use self::check_chat_username_result_public_groups_unavailable::CheckChatUsernameResultPublicGroupsUnavailable;
pub use self::connected_website::ConnectedWebsite;
pub use self::connected_websites::ConnectedWebsites;
pub use self::connection_state::{ConnectionState, RTDConnectionStateType};
pub use self::connection_state_waiting_for_network::ConnectionStateWaitingForNetwork;
pub use self::connection_state_connecting_to_proxy::ConnectionStateConnectingToProxy;
pub use self::connection_state_connecting::ConnectionStateConnecting;
pub use self::connection_state_updating::ConnectionStateUpdating;
pub use self::connection_state_ready::ConnectionStateReady;
pub use self::contact::Contact;
pub use self::count::Count;
pub use self::custom_request_result::CustomRequestResult;
pub use self::database_statistics::DatabaseStatistics;
pub use self::date::Date;
pub use self::dated_file::DatedFile;
pub use self::deep_link_info::DeepLinkInfo;
pub use self::device_token::{DeviceToken, RTDDeviceTokenType};
pub use self::device_token_firebase_cloud_messaging::DeviceTokenFirebaseCloudMessaging;
pub use self::device_token_apple_push::DeviceTokenApplePush;
pub use self::device_token_apple_push_vo_i_p::DeviceTokenApplePushVoIP;
pub use self::device_token_windows_push::DeviceTokenWindowsPush;
pub use self::device_token_microsoft_push::DeviceTokenMicrosoftPush;
pub use self::device_token_microsoft_push_vo_i_p::DeviceTokenMicrosoftPushVoIP;
pub use self::device_token_web_push::DeviceTokenWebPush;
pub use self::device_token_simple_push::DeviceTokenSimplePush;
pub use self::device_token_ubuntu_push::DeviceTokenUbuntuPush;
pub use self::device_token_black_berry_push::DeviceTokenBlackBerryPush;
pub use self::device_token_tizen_push::DeviceTokenTizenPush;
pub use self::document::Document;
pub use self::draft_message::DraftMessage;
pub use self::email_address_authentication_code_info::EmailAddressAuthenticationCodeInfo;
pub use self::encrypted_credentials::EncryptedCredentials;
pub use self::encrypted_passport_element::EncryptedPassportElement;
pub use self::error::Error;
pub use self::file::File;
pub use self::file_part::FilePart;
pub use self::file_type::{FileType, RTDFileTypeType};
pub use self::file_type_none::FileTypeNone;
pub use self::file_type_animation::FileTypeAnimation;
pub use self::file_type_audio::FileTypeAudio;
pub use self::file_type_document::FileTypeDocument;
pub use self::file_type_photo::FileTypePhoto;
pub use self::file_type_profile_photo::FileTypeProfilePhoto;
pub use self::file_type_secret::FileTypeSecret;
pub use self::file_type_secret_thumbnail::FileTypeSecretThumbnail;
pub use self::file_type_secure::FileTypeSecure;
pub use self::file_type_sticker::FileTypeSticker;
pub use self::file_type_thumbnail::FileTypeThumbnail;
pub use self::file_type_unknown::FileTypeUnknown;
pub use self::file_type_video::FileTypeVideo;
pub use self::file_type_video_note::FileTypeVideoNote;
pub use self::file_type_voice_note::FileTypeVoiceNote;
pub use self::file_type_wallpaper::FileTypeWallpaper;
pub use self::formatted_text::FormattedText;
pub use self::found_messages::FoundMessages;
pub use self::game::Game;
pub use self::game_high_score::GameHighScore;
pub use self::game_high_scores::GameHighScores;
pub use self::hashtags::Hashtags;
pub use self::http_url::HttpUrl;
pub use self::identity_document::IdentityDocument;
pub use self::imported_contacts::ImportedContacts;
pub use self::inline_keyboard_button::InlineKeyboardButton;
pub use self::inline_keyboard_button_type::{InlineKeyboardButtonType, RTDInlineKeyboardButtonTypeType};
pub use self::inline_keyboard_button_type_url::InlineKeyboardButtonTypeUrl;
pub use self::inline_keyboard_button_type_callback::InlineKeyboardButtonTypeCallback;
pub use self::inline_keyboard_button_type_callback_game::InlineKeyboardButtonTypeCallbackGame;
pub use self::inline_keyboard_button_type_switch_inline::InlineKeyboardButtonTypeSwitchInline;
pub use self::inline_keyboard_button_type_buy::InlineKeyboardButtonTypeBuy;
pub use self::inline_query_result::{InlineQueryResult, RTDInlineQueryResultType};
pub use self::inline_query_result_article::InlineQueryResultArticle;
pub use self::inline_query_result_contact::InlineQueryResultContact;
pub use self::inline_query_result_location::InlineQueryResultLocation;
pub use self::inline_query_result_venue::InlineQueryResultVenue;
pub use self::inline_query_result_game::InlineQueryResultGame;
pub use self::inline_query_result_animation::InlineQueryResultAnimation;
pub use self::inline_query_result_audio::InlineQueryResultAudio;
pub use self::inline_query_result_document::InlineQueryResultDocument;
pub use self::inline_query_result_photo::InlineQueryResultPhoto;
pub use self::inline_query_result_sticker::InlineQueryResultSticker;
pub use self::inline_query_result_video::InlineQueryResultVideo;
pub use self::inline_query_result_voice_note::InlineQueryResultVoiceNote;
pub use self::inline_query_results::InlineQueryResults;
pub use self::input_credentials::{InputCredentials, RTDInputCredentialsType};
pub use self::input_credentials_saved::InputCredentialsSaved;
pub use self::input_credentials_new::InputCredentialsNew;
pub use self::input_credentials_android_pay::InputCredentialsAndroidPay;
pub use self::input_credentials_apple_pay::InputCredentialsApplePay;
pub use self::input_file::{InputFile, RTDInputFileType};
pub use self::input_file_id::InputFileId;
pub use self::input_file_remote::InputFileRemote;
pub use self::input_file_local::InputFileLocal;
pub use self::input_file_generated::InputFileGenerated;
pub use self::input_identity_document::InputIdentityDocument;
pub use self::input_inline_query_result::{InputInlineQueryResult, RTDInputInlineQueryResultType};
pub use self::input_inline_query_result_animated_gif::InputInlineQueryResultAnimatedGif;
pub use self::input_inline_query_result_animated_mpeg4::InputInlineQueryResultAnimatedMpeg4;
pub use self::input_inline_query_result_article::InputInlineQueryResultArticle;
pub use self::input_inline_query_result_audio::InputInlineQueryResultAudio;
pub use self::input_inline_query_result_contact::InputInlineQueryResultContact;
pub use self::input_inline_query_result_document::InputInlineQueryResultDocument;
pub use self::input_inline_query_result_game::InputInlineQueryResultGame;
pub use self::input_inline_query_result_location::InputInlineQueryResultLocation;
pub use self::input_inline_query_result_photo::InputInlineQueryResultPhoto;
pub use self::input_inline_query_result_sticker::InputInlineQueryResultSticker;
pub use self::input_inline_query_result_venue::InputInlineQueryResultVenue;
pub use self::input_inline_query_result_video::InputInlineQueryResultVideo;
pub use self::input_inline_query_result_voice_note::InputInlineQueryResultVoiceNote;
pub use self::input_message_content::{InputMessageContent, RTDInputMessageContentType};
pub use self::input_message_text::InputMessageText;
pub use self::input_message_animation::InputMessageAnimation;
pub use self::input_message_audio::InputMessageAudio;
pub use self::input_message_document::InputMessageDocument;
pub use self::input_message_photo::InputMessagePhoto;
pub use self::input_message_sticker::InputMessageSticker;
pub use self::input_message_video::InputMessageVideo;
pub use self::input_message_video_note::InputMessageVideoNote;
pub use self::input_message_voice_note::InputMessageVoiceNote;
pub use self::input_message_location::InputMessageLocation;
pub use self::input_message_venue::InputMessageVenue;
pub use self::input_message_contact::InputMessageContact;
pub use self::input_message_game::InputMessageGame;
pub use self::input_message_invoice::InputMessageInvoice;
pub use self::input_message_poll::InputMessagePoll;
pub use self::input_message_forwarded::InputMessageForwarded;
pub use self::input_passport_element::{InputPassportElement, RTDInputPassportElementType};
pub use self::input_passport_element_personal_details::InputPassportElementPersonalDetails;
pub use self::input_passport_element_passport::InputPassportElementPassport;
pub use self::input_passport_element_driver_license::InputPassportElementDriverLicense;
pub use self::input_passport_element_identity_card::InputPassportElementIdentityCard;
pub use self::input_passport_element_internal_passport::InputPassportElementInternalPassport;
pub use self::input_passport_element_address::InputPassportElementAddress;
pub use self::input_passport_element_utility_bill::InputPassportElementUtilityBill;
pub use self::input_passport_element_bank_statement::InputPassportElementBankStatement;
pub use self::input_passport_element_rental_agreement::InputPassportElementRentalAgreement;
pub use self::input_passport_element_passport_registration::InputPassportElementPassportRegistration;
pub use self::input_passport_element_temporary_registration::InputPassportElementTemporaryRegistration;
pub use self::input_passport_element_phone_number::InputPassportElementPhoneNumber;
pub use self::input_passport_element_email_address::InputPassportElementEmailAddress;
pub use self::input_passport_element_error::InputPassportElementError;
pub use self::input_passport_element_error_source::{InputPassportElementErrorSource, RTDInputPassportElementErrorSourceType};
pub use self::input_passport_element_error_source_unspecified::InputPassportElementErrorSourceUnspecified;
pub use self::input_passport_element_error_source_data_field::InputPassportElementErrorSourceDataField;
pub use self::input_passport_element_error_source_front_side::InputPassportElementErrorSourceFrontSide;
pub use self::input_passport_element_error_source_reverse_side::InputPassportElementErrorSourceReverseSide;
pub use self::input_passport_element_error_source_selfie::InputPassportElementErrorSourceSelfie;
pub use self::input_passport_element_error_source_translation_file::InputPassportElementErrorSourceTranslationFile;
pub use self::input_passport_element_error_source_translation_files::InputPassportElementErrorSourceTranslationFiles;
pub use self::input_passport_element_error_source_file::InputPassportElementErrorSourceFile;
pub use self::input_passport_element_error_source_files::InputPassportElementErrorSourceFiles;
pub use self::input_personal_document::InputPersonalDocument;
pub use self::input_sticker::InputSticker;
pub use self::input_thumbnail::InputThumbnail;
pub use self::invoice::Invoice;
pub use self::keyboard_button::KeyboardButton;
pub use self::keyboard_button_type::{KeyboardButtonType, RTDKeyboardButtonTypeType};
pub use self::keyboard_button_type_text::KeyboardButtonTypeText;
pub use self::keyboard_button_type_request_phone_number::KeyboardButtonTypeRequestPhoneNumber;
pub use self::keyboard_button_type_request_location::KeyboardButtonTypeRequestLocation;
pub use self::labeled_price_part::LabeledPricePart;
pub use self::language_pack_info::LanguagePackInfo;
pub use self::language_pack_string::LanguagePackString;
pub use self::language_pack_string_value::{LanguagePackStringValue, RTDLanguagePackStringValueType};
pub use self::language_pack_string_value_ordinary::LanguagePackStringValueOrdinary;
pub use self::language_pack_string_value_pluralized::LanguagePackStringValuePluralized;
pub use self::language_pack_string_value_deleted::LanguagePackStringValueDeleted;
pub use self::language_pack_strings::LanguagePackStrings;
pub use self::link_state::{LinkState, RTDLinkStateType};
pub use self::link_state_none::LinkStateNone;
pub use self::link_state_knows_phone_number::LinkStateKnowsPhoneNumber;
pub use self::link_state_is_contact::LinkStateIsContact;
pub use self::local_file::LocalFile;
pub use self::localization_target_info::LocalizationTargetInfo;
pub use self::location::Location;
pub use self::log_stream::{LogStream, RTDLogStreamType};
pub use self::log_stream_default::LogStreamDefault;
pub use self::log_stream_file::LogStreamFile;
pub use self::log_stream_empty::LogStreamEmpty;
pub use self::log_tags::LogTags;
pub use self::log_verbosity_level::LogVerbosityLevel;
pub use self::mask_point::{MaskPoint, RTDMaskPointType};
pub use self::mask_point_forehead::MaskPointForehead;
pub use self::mask_point_eyes::MaskPointEyes;
pub use self::mask_point_mouth::MaskPointMouth;
pub use self::mask_point_chin::MaskPointChin;
pub use self::mask_position::MaskPosition;
pub use self::message::Message;
pub use self::message_content::{MessageContent, RTDMessageContentType};
pub use self::message_text::MessageText;
pub use self::message_animation::MessageAnimation;
pub use self::message_audio::MessageAudio;
pub use self::message_document::MessageDocument;
pub use self::message_photo::MessagePhoto;
pub use self::message_expired_photo::MessageExpiredPhoto;
pub use self::message_sticker::MessageSticker;
pub use self::message_video::MessageVideo;
pub use self::message_expired_video::MessageExpiredVideo;
pub use self::message_video_note::MessageVideoNote;
pub use self::message_voice_note::MessageVoiceNote;
pub use self::message_location::MessageLocation;
pub use self::message_venue::MessageVenue;
pub use self::message_contact::MessageContact;
pub use self::message_game::MessageGame;
pub use self::message_poll::MessagePoll;
pub use self::message_invoice::MessageInvoice;
pub use self::message_call::MessageCall;
pub use self::message_basic_group_chat_create::MessageBasicGroupChatCreate;
pub use self::message_supergroup_chat_create::MessageSupergroupChatCreate;
pub use self::message_chat_change_title::MessageChatChangeTitle;
pub use self::message_chat_change_photo::MessageChatChangePhoto;
pub use self::message_chat_delete_photo::MessageChatDeletePhoto;
pub use self::message_chat_add_members::MessageChatAddMembers;
pub use self::message_chat_join_by_link::MessageChatJoinByLink;
pub use self::message_chat_delete_member::MessageChatDeleteMember;
pub use self::message_chat_upgrade_to::MessageChatUpgradeTo;
pub use self::message_chat_upgrade_from::MessageChatUpgradeFrom;
pub use self::message_pin_message::MessagePinMessage;
pub use self::message_screenshot_taken::MessageScreenshotTaken;
pub use self::message_chat_set_ttl::MessageChatSetTtl;
pub use self::message_custom_service_action::MessageCustomServiceAction;
pub use self::message_game_score::MessageGameScore;
pub use self::message_payment_successful::MessagePaymentSuccessful;
pub use self::message_payment_successful_bot::MessagePaymentSuccessfulBot;
pub use self::message_contact_registered::MessageContactRegistered;
pub use self::message_website_connected::MessageWebsiteConnected;
pub use self::message_passport_data_sent::MessagePassportDataSent;
pub use self::message_passport_data_received::MessagePassportDataReceived;
pub use self::message_unsupported::MessageUnsupported;
pub use self::message_forward_info::MessageForwardInfo;
pub use self::message_forward_origin::{MessageForwardOrigin, RTDMessageForwardOriginType};
pub use self::message_forward_origin_user::MessageForwardOriginUser;
pub use self::message_forward_origin_hidden_user::MessageForwardOriginHiddenUser;
pub use self::message_forward_origin_channel::MessageForwardOriginChannel;
pub use self::message_sending_state::{MessageSendingState, RTDMessageSendingStateType};
pub use self::message_sending_state_pending::MessageSendingStatePending;
pub use self::message_sending_state_failed::MessageSendingStateFailed;
pub use self::messages::Messages;
pub use self::network_statistics::NetworkStatistics;
pub use self::network_statistics_entry::{NetworkStatisticsEntry, RTDNetworkStatisticsEntryType};
pub use self::network_statistics_entry_file::NetworkStatisticsEntryFile;
pub use self::network_statistics_entry_call::NetworkStatisticsEntryCall;
pub use self::network_type::{NetworkType, RTDNetworkTypeType};
pub use self::network_type_none::NetworkTypeNone;
pub use self::network_type_mobile::NetworkTypeMobile;
pub use self::network_type_mobile_roaming::NetworkTypeMobileRoaming;
pub use self::network_type_wi_fi::NetworkTypeWiFi;
pub use self::network_type_other::NetworkTypeOther;
pub use self::notification::Notification;
pub use self::notification_group::NotificationGroup;
pub use self::notification_group_type::{NotificationGroupType, RTDNotificationGroupTypeType};
pub use self::notification_group_type_messages::NotificationGroupTypeMessages;
pub use self::notification_group_type_mentions::NotificationGroupTypeMentions;
pub use self::notification_group_type_secret_chat::NotificationGroupTypeSecretChat;
pub use self::notification_group_type_calls::NotificationGroupTypeCalls;
pub use self::notification_settings_scope::{NotificationSettingsScope, RTDNotificationSettingsScopeType};
pub use self::notification_settings_scope_private_chats::NotificationSettingsScopePrivateChats;
pub use self::notification_settings_scope_group_chats::NotificationSettingsScopeGroupChats;
pub use self::notification_settings_scope_channel_chats::NotificationSettingsScopeChannelChats;
pub use self::notification_type::{NotificationType, RTDNotificationTypeType};
pub use self::notification_type_new_message::NotificationTypeNewMessage;
pub use self::notification_type_new_secret_chat::NotificationTypeNewSecretChat;
pub use self::notification_type_new_call::NotificationTypeNewCall;
pub use self::notification_type_new_push_message::NotificationTypeNewPushMessage;
pub use self::ok::Ok;
pub use self::option_value::{OptionValue, RTDOptionValueType};
pub use self::option_value_boolean::OptionValueBoolean;
pub use self::option_value_empty::OptionValueEmpty;
pub use self::option_value_integer::OptionValueInteger;
pub use self::option_value_string::OptionValueString;
pub use self::order_info::OrderInfo;
pub use self::page_block::{PageBlock, RTDPageBlockType};
pub use self::page_block_title::PageBlockTitle;
pub use self::page_block_subtitle::PageBlockSubtitle;
pub use self::page_block_author_date::PageBlockAuthorDate;
pub use self::page_block_header::PageBlockHeader;
pub use self::page_block_subheader::PageBlockSubheader;
pub use self::page_block_kicker::PageBlockKicker;
pub use self::page_block_paragraph::PageBlockParagraph;
pub use self::page_block_preformatted::PageBlockPreformatted;
pub use self::page_block_footer::PageBlockFooter;
pub use self::page_block_divider::PageBlockDivider;
pub use self::page_block_anchor::PageBlockAnchor;
pub use self::page_block_list::PageBlockList;
pub use self::page_block_block_quote::PageBlockBlockQuote;
pub use self::page_block_pull_quote::PageBlockPullQuote;
pub use self::page_block_animation::PageBlockAnimation;
pub use self::page_block_audio::PageBlockAudio;
pub use self::page_block_photo::PageBlockPhoto;
pub use self::page_block_video::PageBlockVideo;
pub use self::page_block_cover::PageBlockCover;
pub use self::page_block_embedded::PageBlockEmbedded;
pub use self::page_block_embedded_post::PageBlockEmbeddedPost;
pub use self::page_block_collage::PageBlockCollage;
pub use self::page_block_slideshow::PageBlockSlideshow;
pub use self::page_block_chat_link::PageBlockChatLink;
pub use self::page_block_table::PageBlockTable;
pub use self::page_block_details::PageBlockDetails;
pub use self::page_block_related_articles::PageBlockRelatedArticles;
pub use self::page_block_map::PageBlockMap;
pub use self::page_block_caption::PageBlockCaption;
pub use self::page_block_horizontal_alignment::{PageBlockHorizontalAlignment, RTDPageBlockHorizontalAlignmentType};
pub use self::page_block_horizontal_alignment_left::PageBlockHorizontalAlignmentLeft;
pub use self::page_block_horizontal_alignment_center::PageBlockHorizontalAlignmentCenter;
pub use self::page_block_horizontal_alignment_right::PageBlockHorizontalAlignmentRight;
pub use self::page_block_list_item::PageBlockListItem;
pub use self::page_block_related_article::PageBlockRelatedArticle;
pub use self::page_block_table_cell::PageBlockTableCell;
pub use self::page_block_vertical_alignment::{PageBlockVerticalAlignment, RTDPageBlockVerticalAlignmentType};
pub use self::page_block_vertical_alignment_top::PageBlockVerticalAlignmentTop;
pub use self::page_block_vertical_alignment_middle::PageBlockVerticalAlignmentMiddle;
pub use self::page_block_vertical_alignment_bottom::PageBlockVerticalAlignmentBottom;
pub use self::passport_authorization_form::PassportAuthorizationForm;
pub use self::passport_element::{PassportElement, RTDPassportElementType};
pub use self::passport_element_personal_details::PassportElementPersonalDetails;
pub use self::passport_element_passport::PassportElementPassport;
pub use self::passport_element_driver_license::PassportElementDriverLicense;
pub use self::passport_element_identity_card::PassportElementIdentityCard;
pub use self::passport_element_internal_passport::PassportElementInternalPassport;
pub use self::passport_element_address::PassportElementAddress;
pub use self::passport_element_utility_bill::PassportElementUtilityBill;
pub use self::passport_element_bank_statement::PassportElementBankStatement;
pub use self::passport_element_rental_agreement::PassportElementRentalAgreement;
pub use self::passport_element_passport_registration::PassportElementPassportRegistration;
pub use self::passport_element_temporary_registration::PassportElementTemporaryRegistration;
pub use self::passport_element_phone_number::PassportElementPhoneNumber;
pub use self::passport_element_email_address::PassportElementEmailAddress;
pub use self::passport_element_error::PassportElementError;
pub use self::passport_element_error_source::{PassportElementErrorSource, RTDPassportElementErrorSourceType};
pub use self::passport_element_error_source_unspecified::PassportElementErrorSourceUnspecified;
pub use self::passport_element_error_source_data_field::PassportElementErrorSourceDataField;
pub use self::passport_element_error_source_front_side::PassportElementErrorSourceFrontSide;
pub use self::passport_element_error_source_reverse_side::PassportElementErrorSourceReverseSide;
pub use self::passport_element_error_source_selfie::PassportElementErrorSourceSelfie;
pub use self::passport_element_error_source_translation_file::PassportElementErrorSourceTranslationFile;
pub use self::passport_element_error_source_translation_files::PassportElementErrorSourceTranslationFiles;
pub use self::passport_element_error_source_file::PassportElementErrorSourceFile;
pub use self::passport_element_error_source_files::PassportElementErrorSourceFiles;
pub use self::passport_element_type::{PassportElementType, RTDPassportElementTypeType};
pub use self::passport_element_type_personal_details::PassportElementTypePersonalDetails;
pub use self::passport_element_type_passport::PassportElementTypePassport;
pub use self::passport_element_type_driver_license::PassportElementTypeDriverLicense;
pub use self::passport_element_type_identity_card::PassportElementTypeIdentityCard;
pub use self::passport_element_type_internal_passport::PassportElementTypeInternalPassport;
pub use self::passport_element_type_address::PassportElementTypeAddress;
pub use self::passport_element_type_utility_bill::PassportElementTypeUtilityBill;
pub use self::passport_element_type_bank_statement::PassportElementTypeBankStatement;
pub use self::passport_element_type_rental_agreement::PassportElementTypeRentalAgreement;
pub use self::passport_element_type_passport_registration::PassportElementTypePassportRegistration;
pub use self::passport_element_type_temporary_registration::PassportElementTypeTemporaryRegistration;
pub use self::passport_element_type_phone_number::PassportElementTypePhoneNumber;
pub use self::passport_element_type_email_address::PassportElementTypeEmailAddress;
pub use self::passport_elements::PassportElements;
pub use self::passport_elements_with_errors::PassportElementsWithErrors;
pub use self::passport_required_element::PassportRequiredElement;
pub use self::passport_suitable_element::PassportSuitableElement;
pub use self::password_state::PasswordState;
pub use self::payment_form::PaymentForm;
pub use self::payment_receipt::PaymentReceipt;
pub use self::payment_result::PaymentResult;
pub use self::payments_provider_stripe::PaymentsProviderStripe;
pub use self::personal_details::PersonalDetails;
pub use self::personal_document::PersonalDocument;
pub use self::photo::Photo;
pub use self::photo_size::PhotoSize;
pub use self::poll::Poll;
pub use self::poll_option::PollOption;
pub use self::profile_photo::ProfilePhoto;
pub use self::proxies::Proxies;
pub use self::proxy::Proxy;
pub use self::proxy_type::{ProxyType, RTDProxyTypeType};
pub use self::proxy_type_socks5::ProxyTypeSocks5;
pub use self::proxy_type_http::ProxyTypeHttp;
pub use self::proxy_type_mtproto::ProxyTypeMtproto;
pub use self::public_message_link::PublicMessageLink;
pub use self::push_message_content::{PushMessageContent, RTDPushMessageContentType};
pub use self::push_message_content_hidden::PushMessageContentHidden;
pub use self::push_message_content_animation::PushMessageContentAnimation;
pub use self::push_message_content_audio::PushMessageContentAudio;
pub use self::push_message_content_contact::PushMessageContentContact;
pub use self::push_message_content_contact_registered::PushMessageContentContactRegistered;
pub use self::push_message_content_document::PushMessageContentDocument;
pub use self::push_message_content_game::PushMessageContentGame;
pub use self::push_message_content_game_score::PushMessageContentGameScore;
pub use self::push_message_content_invoice::PushMessageContentInvoice;
pub use self::push_message_content_location::PushMessageContentLocation;
pub use self::push_message_content_photo::PushMessageContentPhoto;
pub use self::push_message_content_poll::PushMessageContentPoll;
pub use self::push_message_content_screenshot_taken::PushMessageContentScreenshotTaken;
pub use self::push_message_content_sticker::PushMessageContentSticker;
pub use self::push_message_content_text::PushMessageContentText;
pub use self::push_message_content_video::PushMessageContentVideo;
pub use self::push_message_content_video_note::PushMessageContentVideoNote;
pub use self::push_message_content_voice_note::PushMessageContentVoiceNote;
pub use self::push_message_content_basic_group_chat_create::PushMessageContentBasicGroupChatCreate;
pub use self::push_message_content_chat_add_members::PushMessageContentChatAddMembers;
pub use self::push_message_content_chat_change_photo::PushMessageContentChatChangePhoto;
pub use self::push_message_content_chat_change_title::PushMessageContentChatChangeTitle;
pub use self::push_message_content_chat_delete_member::PushMessageContentChatDeleteMember;
pub use self::push_message_content_chat_join_by_link::PushMessageContentChatJoinByLink;
pub use self::push_message_content_message_forwards::PushMessageContentMessageForwards;
pub use self::push_message_content_media_album::PushMessageContentMediaAlbum;
pub use self::push_receiver_id::PushReceiverId;
pub use self::recovery_email_address::RecoveryEmailAddress;
pub use self::remote_file::RemoteFile;
pub use self::reply_markup::{ReplyMarkup, RTDReplyMarkupType};
pub use self::reply_markup_remove_keyboard::ReplyMarkupRemoveKeyboard;
pub use self::reply_markup_force_reply::ReplyMarkupForceReply;
pub use self::reply_markup_show_keyboard::ReplyMarkupShowKeyboard;
pub use self::reply_markup_inline_keyboard::ReplyMarkupInlineKeyboard;
pub use self::rich_text::{RichText, RTDRichTextType};
pub use self::rich_text_plain::RichTextPlain;
pub use self::rich_text_bold::RichTextBold;
pub use self::rich_text_italic::RichTextItalic;
pub use self::rich_text_underline::RichTextUnderline;
pub use self::rich_text_strikethrough::RichTextStrikethrough;
pub use self::rich_text_fixed::RichTextFixed;
pub use self::rich_text_url::RichTextUrl;
pub use self::rich_text_email_address::RichTextEmailAddress;
pub use self::rich_text_subscript::RichTextSubscript;
pub use self::rich_text_superscript::RichTextSuperscript;
pub use self::rich_text_marked::RichTextMarked;
pub use self::rich_text_phone_number::RichTextPhoneNumber;
pub use self::rich_text_icon::RichTextIcon;
pub use self::rich_text_anchor::RichTextAnchor;
pub use self::rich_texts::RichTexts;
pub use self::saved_credentials::SavedCredentials;
pub use self::scope_notification_settings::ScopeNotificationSettings;
pub use self::search_messages_filter::{SearchMessagesFilter, RTDSearchMessagesFilterType};
pub use self::search_messages_filter_empty::SearchMessagesFilterEmpty;
pub use self::search_messages_filter_animation::SearchMessagesFilterAnimation;
pub use self::search_messages_filter_audio::SearchMessagesFilterAudio;
pub use self::search_messages_filter_document::SearchMessagesFilterDocument;
pub use self::search_messages_filter_photo::SearchMessagesFilterPhoto;
pub use self::search_messages_filter_video::SearchMessagesFilterVideo;
pub use self::search_messages_filter_voice_note::SearchMessagesFilterVoiceNote;
pub use self::search_messages_filter_photo_and_video::SearchMessagesFilterPhotoAndVideo;
pub use self::search_messages_filter_url::SearchMessagesFilterUrl;
pub use self::search_messages_filter_chat_photo::SearchMessagesFilterChatPhoto;
pub use self::search_messages_filter_call::SearchMessagesFilterCall;
pub use self::search_messages_filter_missed_call::SearchMessagesFilterMissedCall;
pub use self::search_messages_filter_video_note::SearchMessagesFilterVideoNote;
pub use self::search_messages_filter_voice_and_video_note::SearchMessagesFilterVoiceAndVideoNote;
pub use self::search_messages_filter_mention::SearchMessagesFilterMention;
pub use self::search_messages_filter_unread_mention::SearchMessagesFilterUnreadMention;
pub use self::seconds::Seconds;
pub use self::secret_chat::SecretChat;
pub use self::secret_chat_state::{SecretChatState, RTDSecretChatStateType};
pub use self::secret_chat_state_pending::SecretChatStatePending;
pub use self::secret_chat_state_ready::SecretChatStateReady;
pub use self::secret_chat_state_closed::SecretChatStateClosed;
pub use self::session::Session;
pub use self::sessions::Sessions;
pub use self::shipping_option::ShippingOption;
pub use self::sticker::Sticker;
pub use self::sticker_emojis::StickerEmojis;
pub use self::sticker_set::StickerSet;
pub use self::sticker_set_info::StickerSetInfo;
pub use self::sticker_sets::StickerSets;
pub use self::stickers::Stickers;
pub use self::storage_statistics::StorageStatistics;
pub use self::storage_statistics_by_chat::StorageStatisticsByChat;
pub use self::storage_statistics_by_file_type::StorageStatisticsByFileType;
pub use self::storage_statistics_fast::StorageStatisticsFast;
pub use self::supergroup::Supergroup;
pub use self::supergroup_full_info::SupergroupFullInfo;
pub use self::supergroup_members_filter::{SupergroupMembersFilter, RTDSupergroupMembersFilterType};
pub use self::supergroup_members_filter_recent::SupergroupMembersFilterRecent;
pub use self::supergroup_members_filter_administrators::SupergroupMembersFilterAdministrators;
pub use self::supergroup_members_filter_search::SupergroupMembersFilterSearch;
pub use self::supergroup_members_filter_restricted::SupergroupMembersFilterRestricted;
pub use self::supergroup_members_filter_banned::SupergroupMembersFilterBanned;
pub use self::supergroup_members_filter_bots::SupergroupMembersFilterBots;
pub use self::t_me_url::TMeUrl;
pub use self::t_me_url_type::{TMeUrlType, RTDTMeUrlTypeType};
pub use self::t_me_url_type_user::TMeUrlTypeUser;
pub use self::t_me_url_type_supergroup::TMeUrlTypeSupergroup;
pub use self::t_me_url_type_chat_invite::TMeUrlTypeChatInvite;
pub use self::t_me_url_type_sticker_set::TMeUrlTypeStickerSet;
pub use self::t_me_urls::TMeUrls;
pub use self::tdlib_parameters::TdlibParameters;
pub use self::temporary_password_state::TemporaryPasswordState;
pub use self::terms_of_service::TermsOfService;
pub use self::test_bytes::TestBytes;
pub use self::test_int::TestInt;
pub use self::test_string::TestString;
pub use self::test_vector_int::TestVectorInt;
pub use self::test_vector_int_object::TestVectorIntObject;
pub use self::test_vector_string::TestVectorString;
pub use self::test_vector_string_object::TestVectorStringObject;
pub use self::text::Text;
pub use self::text_entities::TextEntities;
pub use self::text_entity::TextEntity;
pub use self::text_entity_type::{TextEntityType, RTDTextEntityTypeType};
pub use self::text_entity_type_mention::TextEntityTypeMention;
pub use self::text_entity_type_hashtag::TextEntityTypeHashtag;
pub use self::text_entity_type_cashtag::TextEntityTypeCashtag;
pub use self::text_entity_type_bot_command::TextEntityTypeBotCommand;
pub use self::text_entity_type_url::TextEntityTypeUrl;
pub use self::text_entity_type_email_address::TextEntityTypeEmailAddress;
pub use self::text_entity_type_bold::TextEntityTypeBold;
pub use self::text_entity_type_italic::TextEntityTypeItalic;
pub use self::text_entity_type_code::TextEntityTypeCode;
pub use self::text_entity_type_pre::TextEntityTypePre;
pub use self::text_entity_type_pre_code::TextEntityTypePreCode;
pub use self::text_entity_type_text_url::TextEntityTypeTextUrl;
pub use self::text_entity_type_mention_name::TextEntityTypeMentionName;
pub use self::text_entity_type_phone_number::TextEntityTypePhoneNumber;
pub use self::text_parse_mode::{TextParseMode, RTDTextParseModeType};
pub use self::text_parse_mode_markdown::TextParseModeMarkdown;
pub use self::text_parse_mode_h_t_m_l::TextParseModeHTML;
pub use self::top_chat_category::{TopChatCategory, RTDTopChatCategoryType};
pub use self::top_chat_category_users::TopChatCategoryUsers;
pub use self::top_chat_category_bots::TopChatCategoryBots;
pub use self::top_chat_category_groups::TopChatCategoryGroups;
pub use self::top_chat_category_channels::TopChatCategoryChannels;
pub use self::top_chat_category_inline_bots::TopChatCategoryInlineBots;
pub use self::top_chat_category_calls::TopChatCategoryCalls;
pub use self::update::{Update, RTDUpdateType};
pub use self::update_authorization_state::UpdateAuthorizationState;
pub use self::update_new_message::UpdateNewMessage;
pub use self::update_message_send_acknowledged::UpdateMessageSendAcknowledged;
pub use self::update_message_send_succeeded::UpdateMessageSendSucceeded;
pub use self::update_message_send_failed::UpdateMessageSendFailed;
pub use self::update_message_content::UpdateMessageContent;
pub use self::update_message_edited::UpdateMessageEdited;
pub use self::update_message_views::UpdateMessageViews;
pub use self::update_message_content_opened::UpdateMessageContentOpened;
pub use self::update_message_mention_read::UpdateMessageMentionRead;
pub use self::update_new_chat::UpdateNewChat;
pub use self::update_chat_title::UpdateChatTitle;
pub use self::update_chat_photo::UpdateChatPhoto;
pub use self::update_chat_last_message::UpdateChatLastMessage;
pub use self::update_chat_order::UpdateChatOrder;
pub use self::update_chat_is_pinned::UpdateChatIsPinned;
pub use self::update_chat_is_marked_as_unread::UpdateChatIsMarkedAsUnread;
pub use self::update_chat_is_sponsored::UpdateChatIsSponsored;
pub use self::update_chat_default_disable_notification::UpdateChatDefaultDisableNotification;
pub use self::update_chat_read_inbox::UpdateChatReadInbox;
pub use self::update_chat_read_outbox::UpdateChatReadOutbox;
pub use self::update_chat_unread_mention_count::UpdateChatUnreadMentionCount;
pub use self::update_chat_notification_settings::UpdateChatNotificationSettings;
pub use self::update_scope_notification_settings::UpdateScopeNotificationSettings;
pub use self::update_chat_pinned_message::UpdateChatPinnedMessage;
pub use self::update_chat_reply_markup::UpdateChatReplyMarkup;
pub use self::update_chat_draft_message::UpdateChatDraftMessage;
pub use self::update_chat_online_member_count::UpdateChatOnlineMemberCount;
pub use self::update_notification::UpdateNotification;
pub use self::update_notification_group::UpdateNotificationGroup;
pub use self::update_active_notifications::UpdateActiveNotifications;
pub use self::update_have_pending_notifications::UpdateHavePendingNotifications;
pub use self::update_delete_messages::UpdateDeleteMessages;
pub use self::update_user_chat_action::UpdateUserChatAction;
pub use self::update_user_status::UpdateUserStatus;
pub use self::update_user::UpdateUser;
pub use self::update_basic_group::UpdateBasicGroup;
pub use self::update_supergroup::UpdateSupergroup;
pub use self::update_secret_chat::UpdateSecretChat;
pub use self::update_user_full_info::UpdateUserFullInfo;
pub use self::update_basic_group_full_info::UpdateBasicGroupFullInfo;
pub use self::update_supergroup_full_info::UpdateSupergroupFullInfo;
pub use self::update_service_notification::UpdateServiceNotification;
pub use self::update_file::UpdateFile;
pub use self::update_file_generation_start::UpdateFileGenerationStart;
pub use self::update_file_generation_stop::UpdateFileGenerationStop;
pub use self::update_call::UpdateCall;
pub use self::update_user_privacy_setting_rules::UpdateUserPrivacySettingRules;
pub use self::update_unread_message_count::UpdateUnreadMessageCount;
pub use self::update_unread_chat_count::UpdateUnreadChatCount;
pub use self::update_option::UpdateOption;
pub use self::update_installed_sticker_sets::UpdateInstalledStickerSets;
pub use self::update_trending_sticker_sets::UpdateTrendingStickerSets;
pub use self::update_recent_stickers::UpdateRecentStickers;
pub use self::update_favorite_stickers::UpdateFavoriteStickers;
pub use self::update_saved_animations::UpdateSavedAnimations;
pub use self::update_language_pack_strings::UpdateLanguagePackStrings;
pub use self::update_connection_state::UpdateConnectionState;
pub use self::update_terms_of_service::UpdateTermsOfService;
pub use self::update_new_inline_query::UpdateNewInlineQuery;
pub use self::update_new_chosen_inline_result::UpdateNewChosenInlineResult;
pub use self::update_new_callback_query::UpdateNewCallbackQuery;
pub use self::update_new_inline_callback_query::UpdateNewInlineCallbackQuery;
pub use self::update_new_shipping_query::UpdateNewShippingQuery;
pub use self::update_new_pre_checkout_query::UpdateNewPreCheckoutQuery;
pub use self::update_new_custom_event::UpdateNewCustomEvent;
pub use self::update_new_custom_query::UpdateNewCustomQuery;
pub use self::update_poll::UpdatePoll;
pub use self::updates::Updates;
pub use self::user::User;
pub use self::user_full_info::UserFullInfo;
pub use self::user_privacy_setting::{UserPrivacySetting, RTDUserPrivacySettingType};
pub use self::user_privacy_setting_show_status::UserPrivacySettingShowStatus;
pub use self::user_privacy_setting_allow_chat_invites::UserPrivacySettingAllowChatInvites;
pub use self::user_privacy_setting_allow_calls::UserPrivacySettingAllowCalls;
pub use self::user_privacy_setting_allow_peer_to_peer_calls::UserPrivacySettingAllowPeerToPeerCalls;
pub use self::user_privacy_setting_rule::{UserPrivacySettingRule, RTDUserPrivacySettingRuleType};
pub use self::user_privacy_setting_rule_allow_all::UserPrivacySettingRuleAllowAll;
pub use self::user_privacy_setting_rule_allow_contacts::UserPrivacySettingRuleAllowContacts;
pub use self::user_privacy_setting_rule_allow_users::UserPrivacySettingRuleAllowUsers;
pub use self::user_privacy_setting_rule_restrict_all::UserPrivacySettingRuleRestrictAll;
pub use self::user_privacy_setting_rule_restrict_contacts::UserPrivacySettingRuleRestrictContacts;
pub use self::user_privacy_setting_rule_restrict_users::UserPrivacySettingRuleRestrictUsers;
pub use self::user_privacy_setting_rules::UserPrivacySettingRules;
pub use self::user_profile_photo::UserProfilePhoto;
pub use self::user_profile_photos::UserProfilePhotos;
pub use self::user_status::{UserStatus, RTDUserStatusType};
pub use self::user_status_empty::UserStatusEmpty;
pub use self::user_status_online::UserStatusOnline;
pub use self::user_status_offline::UserStatusOffline;
pub use self::user_status_recently::UserStatusRecently;
pub use self::user_status_last_week::UserStatusLastWeek;
pub use self::user_status_last_month::UserStatusLastMonth;
pub use self::user_type::{UserType, RTDUserTypeType};
pub use self::user_type_regular::UserTypeRegular;
pub use self::user_type_deleted::UserTypeDeleted;
pub use self::user_type_bot::UserTypeBot;
pub use self::user_type_unknown::UserTypeUnknown;
pub use self::users::Users;
pub use self::validated_order_info::ValidatedOrderInfo;
pub use self::venue::Venue;
pub use self::video::Video;
pub use self::video_note::VideoNote;
pub use self::voice_note::VoiceNote;
pub use self::wallpaper::Wallpaper;
pub use self::wallpapers::Wallpapers;
pub use self::web_page::WebPage;
pub use self::web_page_instant_view::WebPageInstantView;
pub use self::accept_call::AcceptCall;
pub use self::accept_terms_of_service::AcceptTermsOfService;
pub use self::add_chat_member::AddChatMember;
pub use self::add_chat_members::AddChatMembers;
pub use self::add_custom_server_language_pack::AddCustomServerLanguagePack;
pub use self::add_favorite_sticker::AddFavoriteSticker;
pub use self::add_local_message::AddLocalMessage;
pub use self::add_log_message::AddLogMessage;
pub use self::add_network_statistics::AddNetworkStatistics;
pub use self::add_proxy::AddProxy;
pub use self::add_recent_sticker::AddRecentSticker;
pub use self::add_recently_found_chat::AddRecentlyFoundChat;
pub use self::add_saved_animation::AddSavedAnimation;
pub use self::add_sticker_to_set::AddStickerToSet;
pub use self::answer_callback_query::AnswerCallbackQuery;
pub use self::answer_custom_query::AnswerCustomQuery;
pub use self::answer_inline_query::AnswerInlineQuery;
pub use self::answer_pre_checkout_query::AnswerPreCheckoutQuery;
pub use self::answer_shipping_query::AnswerShippingQuery;
pub use self::block_user::BlockUser;
pub use self::cancel_download_file::CancelDownloadFile;
pub use self::cancel_upload_file::CancelUploadFile;
pub use self::change_chat_report_spam_state::ChangeChatReportSpamState;
pub use self::change_imported_contacts::ChangeImportedContacts;
pub use self::change_phone_number::ChangePhoneNumber;
pub use self::change_sticker_set::ChangeStickerSet;
pub use self::check_authentication_bot_token::CheckAuthenticationBotToken;
pub use self::check_authentication_code::CheckAuthenticationCode;
pub use self::check_authentication_password::CheckAuthenticationPassword;
pub use self::check_change_phone_number_code::CheckChangePhoneNumberCode;
pub use self::check_chat_invite_link::CheckChatInviteLink;
pub use self::check_chat_username::CheckChatUsername;
pub use self::check_database_encryption_key::CheckDatabaseEncryptionKey;
pub use self::check_email_address_verification_code::CheckEmailAddressVerificationCode;
pub use self::check_phone_number_confirmation_code::CheckPhoneNumberConfirmationCode;
pub use self::check_phone_number_verification_code::CheckPhoneNumberVerificationCode;
pub use self::check_recovery_email_address_code::CheckRecoveryEmailAddressCode;
pub use self::clean_file_name::CleanFileName;
pub use self::clear_all_draft_messages::ClearAllDraftMessages;
pub use self::clear_imported_contacts::ClearImportedContacts;
pub use self::clear_recent_stickers::ClearRecentStickers;
pub use self::clear_recently_found_chats::ClearRecentlyFoundChats;
pub use self::close::Close;
pub use self::close_chat::CloseChat;
pub use self::close_secret_chat::CloseSecretChat;
pub use self::create_basic_group_chat::CreateBasicGroupChat;
pub use self::create_call::CreateCall;
pub use self::create_new_basic_group_chat::CreateNewBasicGroupChat;
pub use self::create_new_secret_chat::CreateNewSecretChat;
pub use self::create_new_sticker_set::CreateNewStickerSet;
pub use self::create_new_supergroup_chat::CreateNewSupergroupChat;
pub use self::create_private_chat::CreatePrivateChat;
pub use self::create_secret_chat::CreateSecretChat;
pub use self::create_supergroup_chat::CreateSupergroupChat;
pub use self::create_temporary_password::CreateTemporaryPassword;
pub use self::delete_account::DeleteAccount;
pub use self::delete_chat_history::DeleteChatHistory;
pub use self::delete_chat_messages_from_user::DeleteChatMessagesFromUser;
pub use self::delete_chat_reply_markup::DeleteChatReplyMarkup;
pub use self::delete_file::DeleteFile;
pub use self::delete_language_pack::DeleteLanguagePack;
pub use self::delete_messages::DeleteMessages;
pub use self::delete_passport_element::DeletePassportElement;
pub use self::delete_profile_photo::DeleteProfilePhoto;
pub use self::delete_saved_credentials::DeleteSavedCredentials;
pub use self::delete_saved_order_info::DeleteSavedOrderInfo;
pub use self::delete_supergroup::DeleteSupergroup;
pub use self::destroy::Destroy;
pub use self::disable_proxy::DisableProxy;
pub use self::discard_call::DiscardCall;
pub use self::disconnect_all_websites::DisconnectAllWebsites;
pub use self::disconnect_website::DisconnectWebsite;
pub use self::download_file::DownloadFile;
pub use self::edit_custom_language_pack_info::EditCustomLanguagePackInfo;
pub use self::edit_inline_message_caption::EditInlineMessageCaption;
pub use self::edit_inline_message_live_location::EditInlineMessageLiveLocation;
pub use self::edit_inline_message_media::EditInlineMessageMedia;
pub use self::edit_inline_message_reply_markup::EditInlineMessageReplyMarkup;
pub use self::edit_inline_message_text::EditInlineMessageText;
pub use self::edit_message_caption::EditMessageCaption;
pub use self::edit_message_live_location::EditMessageLiveLocation;
pub use self::edit_message_media::EditMessageMedia;
pub use self::edit_message_reply_markup::EditMessageReplyMarkup;
pub use self::edit_message_text::EditMessageText;
pub use self::edit_proxy::EditProxy;
pub use self::enable_proxy::EnableProxy;
pub use self::finish_file_generation::FinishFileGeneration;
pub use self::forward_messages::ForwardMessages;
pub use self::generate_chat_invite_link::GenerateChatInviteLink;
pub use self::get_account_ttl::GetAccountTtl;
pub use self::get_active_live_location_messages::GetActiveLiveLocationMessages;
pub use self::get_active_sessions::GetActiveSessions;
pub use self::get_all_passport_elements::GetAllPassportElements;
pub use self::get_application_config::GetApplicationConfig;
pub use self::get_archived_sticker_sets::GetArchivedStickerSets;
pub use self::get_attached_sticker_sets::GetAttachedStickerSets;
pub use self::get_authorization_state::GetAuthorizationState;
pub use self::get_basic_group::GetBasicGroup;
pub use self::get_basic_group_full_info::GetBasicGroupFullInfo;
pub use self::get_blocked_users::GetBlockedUsers;
pub use self::get_callback_query_answer::GetCallbackQueryAnswer;
pub use self::get_chat::GetChat;
pub use self::get_chat_administrators::GetChatAdministrators;
pub use self::get_chat_event_log::GetChatEventLog;
pub use self::get_chat_history::GetChatHistory;
pub use self::get_chat_member::GetChatMember;
pub use self::get_chat_message_by_date::GetChatMessageByDate;
pub use self::get_chat_message_count::GetChatMessageCount;
pub use self::get_chat_notification_settings_exceptions::GetChatNotificationSettingsExceptions;
pub use self::get_chat_pinned_message::GetChatPinnedMessage;
pub use self::get_chat_report_spam_state::GetChatReportSpamState;
pub use self::get_chat_statistics_url::GetChatStatisticsUrl;
pub use self::get_chats::GetChats;
pub use self::get_connected_websites::GetConnectedWebsites;
pub use self::get_contacts::GetContacts;
pub use self::get_country_code::GetCountryCode;
pub use self::get_created_public_chats::GetCreatedPublicChats;
pub use self::get_current_state::GetCurrentState;
pub use self::get_database_statistics::GetDatabaseStatistics;
pub use self::get_deep_link_info::GetDeepLinkInfo;
pub use self::get_favorite_stickers::GetFavoriteStickers;
pub use self::get_file::GetFile;
pub use self::get_file_downloaded_prefix_size::GetFileDownloadedPrefixSize;
pub use self::get_file_extension::GetFileExtension;
pub use self::get_file_mime_type::GetFileMimeType;
pub use self::get_game_high_scores::GetGameHighScores;
pub use self::get_groups_in_common::GetGroupsInCommon;
pub use self::get_imported_contact_count::GetImportedContactCount;
pub use self::get_inline_game_high_scores::GetInlineGameHighScores;
pub use self::get_inline_query_results::GetInlineQueryResults;
pub use self::get_installed_sticker_sets::GetInstalledStickerSets;
pub use self::get_invite_text::GetInviteText;
pub use self::get_language_pack_info::GetLanguagePackInfo;
pub use self::get_language_pack_string::GetLanguagePackString;
pub use self::get_language_pack_strings::GetLanguagePackStrings;
pub use self::get_localization_target_info::GetLocalizationTargetInfo;
pub use self::get_log_stream::GetLogStream;
pub use self::get_log_tag_verbosity_level::GetLogTagVerbosityLevel;
pub use self::get_log_tags::GetLogTags;
pub use self::get_log_verbosity_level::GetLogVerbosityLevel;
pub use self::get_map_thumbnail_file::GetMapThumbnailFile;
pub use self::get_me::GetMe;
pub use self::get_message::GetMessage;
pub use self::get_message_link::GetMessageLink;
pub use self::get_message_locally::GetMessageLocally;
pub use self::get_messages::GetMessages;
pub use self::get_network_statistics::GetNetworkStatistics;
pub use self::get_option::GetOption;
pub use self::get_passport_authorization_form::GetPassportAuthorizationForm;
pub use self::get_passport_authorization_form_available_elements::GetPassportAuthorizationFormAvailableElements;
pub use self::get_passport_element::GetPassportElement;
pub use self::get_password_state::GetPasswordState;
pub use self::get_payment_form::GetPaymentForm;
pub use self::get_payment_receipt::GetPaymentReceipt;
pub use self::get_preferred_country_language::GetPreferredCountryLanguage;
pub use self::get_proxies::GetProxies;
pub use self::get_proxy_link::GetProxyLink;
pub use self::get_public_message_link::GetPublicMessageLink;
pub use self::get_push_receiver_id::GetPushReceiverId;
pub use self::get_recent_inline_bots::GetRecentInlineBots;
pub use self::get_recent_stickers::GetRecentStickers;
pub use self::get_recently_visited_t_me_urls::GetRecentlyVisitedTMeUrls;
pub use self::get_recovery_email_address::GetRecoveryEmailAddress;
pub use self::get_remote_file::GetRemoteFile;
pub use self::get_replied_message::GetRepliedMessage;
pub use self::get_saved_animations::GetSavedAnimations;
pub use self::get_saved_order_info::GetSavedOrderInfo;
pub use self::get_scope_notification_settings::GetScopeNotificationSettings;
pub use self::get_secret_chat::GetSecretChat;
pub use self::get_sticker_emojis::GetStickerEmojis;
pub use self::get_sticker_set::GetStickerSet;
pub use self::get_stickers::GetStickers;
pub use self::get_storage_statistics::GetStorageStatistics;
pub use self::get_storage_statistics_fast::GetStorageStatisticsFast;
pub use self::get_supergroup::GetSupergroup;
pub use self::get_supergroup_full_info::GetSupergroupFullInfo;
pub use self::get_supergroup_members::GetSupergroupMembers;
pub use self::get_support_user::GetSupportUser;
pub use self::get_temporary_password_state::GetTemporaryPasswordState;
pub use self::get_text_entities::GetTextEntities;
pub use self::get_top_chats::GetTopChats;
pub use self::get_trending_sticker_sets::GetTrendingStickerSets;
pub use self::get_user::GetUser;
pub use self::get_user_full_info::GetUserFullInfo;
pub use self::get_user_privacy_setting_rules::GetUserPrivacySettingRules;
pub use self::get_user_profile_photos::GetUserProfilePhotos;
pub use self::get_wallpapers::GetWallpapers;
pub use self::get_web_page_instant_view::GetWebPageInstantView;
pub use self::get_web_page_preview::GetWebPagePreview;
pub use self::import_contacts::ImportContacts;
pub use self::join_chat::JoinChat;
pub use self::join_chat_by_invite_link::JoinChatByInviteLink;
pub use self::leave_chat::LeaveChat;
pub use self::log_out::LogOut;
pub use self::open_chat::OpenChat;
pub use self::open_message_content::OpenMessageContent;
pub use self::optimize_storage::OptimizeStorage;
pub use self::parse_text_entities::ParseTextEntities;
pub use self::pin_chat_message::PinChatMessage;
pub use self::ping_proxy::PingProxy;
pub use self::process_push_notification::ProcessPushNotification;
pub use self::read_all_chat_mentions::ReadAllChatMentions;
pub use self::read_file_part::ReadFilePart;
pub use self::recover_authentication_password::RecoverAuthenticationPassword;
pub use self::recover_password::RecoverPassword;
pub use self::register_device::RegisterDevice;
pub use self::remove_contacts::RemoveContacts;
pub use self::remove_favorite_sticker::RemoveFavoriteSticker;
pub use self::remove_notification::RemoveNotification;
pub use self::remove_notification_group::RemoveNotificationGroup;
pub use self::remove_proxy::RemoveProxy;
pub use self::remove_recent_hashtag::RemoveRecentHashtag;
pub use self::remove_recent_sticker::RemoveRecentSticker;
pub use self::remove_recently_found_chat::RemoveRecentlyFoundChat;
pub use self::remove_saved_animation::RemoveSavedAnimation;
pub use self::remove_sticker_from_set::RemoveStickerFromSet;
pub use self::remove_top_chat::RemoveTopChat;
pub use self::reorder_installed_sticker_sets::ReorderInstalledStickerSets;
pub use self::report_chat::ReportChat;
pub use self::report_supergroup_spam::ReportSupergroupSpam;
pub use self::request_authentication_password_recovery::RequestAuthenticationPasswordRecovery;
pub use self::request_password_recovery::RequestPasswordRecovery;
pub use self::resend_authentication_code::ResendAuthenticationCode;
pub use self::resend_change_phone_number_code::ResendChangePhoneNumberCode;
pub use self::resend_email_address_verification_code::ResendEmailAddressVerificationCode;
pub use self::resend_phone_number_confirmation_code::ResendPhoneNumberConfirmationCode;
pub use self::resend_phone_number_verification_code::ResendPhoneNumberVerificationCode;
pub use self::resend_recovery_email_address_code::ResendRecoveryEmailAddressCode;
pub use self::reset_all_notification_settings::ResetAllNotificationSettings;
pub use self::reset_network_statistics::ResetNetworkStatistics;
pub use self::search_call_messages::SearchCallMessages;
pub use self::search_chat_members::SearchChatMembers;
pub use self::search_chat_messages::SearchChatMessages;
pub use self::search_chat_recent_location_messages::SearchChatRecentLocationMessages;
pub use self::search_chats::SearchChats;
pub use self::search_chats_on_server::SearchChatsOnServer;
pub use self::search_contacts::SearchContacts;
pub use self::search_hashtags::SearchHashtags;
pub use self::search_installed_sticker_sets::SearchInstalledStickerSets;
pub use self::search_messages::SearchMessages;
pub use self::search_public_chat::SearchPublicChat;
pub use self::search_public_chats::SearchPublicChats;
pub use self::search_secret_messages::SearchSecretMessages;
pub use self::search_sticker_set::SearchStickerSet;
pub use self::search_sticker_sets::SearchStickerSets;
pub use self::search_stickers::SearchStickers;
pub use self::send_bot_start_message::SendBotStartMessage;
pub use self::send_call_debug_information::SendCallDebugInformation;
pub use self::send_call_rating::SendCallRating;
pub use self::send_chat_action::SendChatAction;
pub use self::send_chat_screenshot_taken_notification::SendChatScreenshotTakenNotification;
pub use self::send_chat_set_ttl_message::SendChatSetTtlMessage;
pub use self::send_custom_request::SendCustomRequest;
pub use self::send_email_address_verification_code::SendEmailAddressVerificationCode;
pub use self::send_inline_query_result_message::SendInlineQueryResultMessage;
pub use self::send_message::SendMessage;
pub use self::send_message_album::SendMessageAlbum;
pub use self::send_passport_authorization_form::SendPassportAuthorizationForm;
pub use self::send_payment_form::SendPaymentForm;
pub use self::send_phone_number_confirmation_code::SendPhoneNumberConfirmationCode;
pub use self::send_phone_number_verification_code::SendPhoneNumberVerificationCode;
pub use self::set_account_ttl::SetAccountTtl;
pub use self::set_alarm::SetAlarm;
pub use self::set_authentication_phone_number::SetAuthenticationPhoneNumber;
pub use self::set_bio::SetBio;
pub use self::set_bot_updates_status::SetBotUpdatesStatus;
pub use self::set_chat_client_data::SetChatClientData;
pub use self::set_chat_draft_message::SetChatDraftMessage;
pub use self::set_chat_member_status::SetChatMemberStatus;
pub use self::set_chat_notification_settings::SetChatNotificationSettings;
pub use self::set_chat_photo::SetChatPhoto;
pub use self::set_chat_title::SetChatTitle;
pub use self::set_custom_language_pack::SetCustomLanguagePack;
pub use self::set_custom_language_pack_string::SetCustomLanguagePackString;
pub use self::set_database_encryption_key::SetDatabaseEncryptionKey;
pub use self::set_file_generation_progress::SetFileGenerationProgress;
pub use self::set_game_score::SetGameScore;
pub use self::set_inline_game_score::SetInlineGameScore;
pub use self::set_log_stream::SetLogStream;
pub use self::set_log_tag_verbosity_level::SetLogTagVerbosityLevel;
pub use self::set_log_verbosity_level::SetLogVerbosityLevel;
pub use self::set_name::SetName;
pub use self::set_network_type::SetNetworkType;
pub use self::set_option::SetOption;
pub use self::set_passport_element::SetPassportElement;
pub use self::set_passport_element_errors::SetPassportElementErrors;
pub use self::set_password::SetPassword;
pub use self::set_pinned_chats::SetPinnedChats;
pub use self::set_poll_answer::SetPollAnswer;
pub use self::set_profile_photo::SetProfilePhoto;
pub use self::set_recovery_email_address::SetRecoveryEmailAddress;
pub use self::set_scope_notification_settings::SetScopeNotificationSettings;
pub use self::set_sticker_position_in_set::SetStickerPositionInSet;
pub use self::set_supergroup_description::SetSupergroupDescription;
pub use self::set_supergroup_sticker_set::SetSupergroupStickerSet;
pub use self::set_supergroup_username::SetSupergroupUsername;
pub use self::set_tdlib_parameters::SetTdlibParameters;
pub use self::set_user_privacy_setting_rules::SetUserPrivacySettingRules;
pub use self::set_username::SetUsername;
pub use self::stop_poll::StopPoll;
pub use self::synchronize_language_pack::SynchronizeLanguagePack;
pub use self::terminate_all_other_sessions::TerminateAllOtherSessions;
pub use self::terminate_session::TerminateSession;
pub use self::test_call_bytes::TestCallBytes;
pub use self::test_call_empty::TestCallEmpty;
pub use self::test_call_string::TestCallString;
pub use self::test_call_vector_int::TestCallVectorInt;
pub use self::test_call_vector_int_object::TestCallVectorIntObject;
pub use self::test_call_vector_string::TestCallVectorString;
pub use self::test_call_vector_string_object::TestCallVectorStringObject;
pub use self::test_get_difference::TestGetDifference;
pub use self::test_network::TestNetwork;
pub use self::test_square_int::TestSquareInt;
pub use self::test_use_error::TestUseError;
pub use self::test_use_update::TestUseUpdate;
pub use self::toggle_basic_group_administrators::ToggleBasicGroupAdministrators;
pub use self::toggle_chat_default_disable_notification::ToggleChatDefaultDisableNotification;
pub use self::toggle_chat_is_marked_as_unread::ToggleChatIsMarkedAsUnread;
pub use self::toggle_chat_is_pinned::ToggleChatIsPinned;
pub use self::toggle_supergroup_invites::ToggleSupergroupInvites;
pub use self::toggle_supergroup_is_all_history_available::ToggleSupergroupIsAllHistoryAvailable;
pub use self::toggle_supergroup_sign_messages::ToggleSupergroupSignMessages;
pub use self::unblock_user::UnblockUser;
pub use self::unpin_chat_message::UnpinChatMessage;
pub use self::upgrade_basic_group_chat_to_supergroup_chat::UpgradeBasicGroupChatToSupergroupChat;
pub use self::upload_file::UploadFile;
pub use self::upload_sticker_file::UploadStickerFile;
pub use self::validate_order_info::ValidateOrderInfo;
pub use self::view_messages::ViewMessages;
pub use self::view_trending_sticker_sets::ViewTrendingStickerSets;
pub use self::write_generated_file_part::WriteGeneratedFilePart;



mod object;
mod function;
mod account_ttl;
mod address;
mod animation;
mod animations;
mod audio;
mod authentication_code_info;
mod authentication_code_type;
mod authentication_code_type_telegram_message;
mod authentication_code_type_sms;
mod authentication_code_type_call;
mod authentication_code_type_flash_call;
mod authorization_state;
mod authorization_state_wait_tdlib_parameters;
mod authorization_state_wait_encryption_key;
mod authorization_state_wait_phone_number;
mod authorization_state_wait_code;
mod authorization_state_wait_password;
mod authorization_state_ready;
mod authorization_state_logging_out;
mod authorization_state_closing;
mod authorization_state_closed;
mod basic_group;
mod basic_group_full_info;
mod bot_command;
mod bot_info;
mod call;
mod call_connection;
mod call_discard_reason;
mod call_discard_reason_empty;
mod call_discard_reason_missed;
mod call_discard_reason_declined;
mod call_discard_reason_disconnected;
mod call_discard_reason_hung_up;
mod call_id;
mod call_protocol;
mod call_state;
mod call_state_pending;
mod call_state_exchanging_keys;
mod call_state_ready;
mod call_state_hanging_up;
mod call_state_discarded;
mod call_state_error;
mod callback_query_answer;
mod callback_query_payload;
mod callback_query_payload_data;
mod callback_query_payload_game;
mod chat;
mod chat_action;
mod chat_action_typing;
mod chat_action_recording_video;
mod chat_action_uploading_video;
mod chat_action_recording_voice_note;
mod chat_action_uploading_voice_note;
mod chat_action_uploading_photo;
mod chat_action_uploading_document;
mod chat_action_choosing_location;
mod chat_action_choosing_contact;
mod chat_action_start_playing_game;
mod chat_action_recording_video_note;
mod chat_action_uploading_video_note;
mod chat_action_cancel;
mod chat_event;
mod chat_event_action;
mod chat_event_message_edited;
mod chat_event_message_deleted;
mod chat_event_message_pinned;
mod chat_event_message_unpinned;
mod chat_event_member_joined;
mod chat_event_member_left;
mod chat_event_member_invited;
mod chat_event_member_promoted;
mod chat_event_member_restricted;
mod chat_event_title_changed;
mod chat_event_description_changed;
mod chat_event_username_changed;
mod chat_event_photo_changed;
mod chat_event_invites_toggled;
mod chat_event_sign_messages_toggled;
mod chat_event_sticker_set_changed;
mod chat_event_is_all_history_available_toggled;
mod chat_event_log_filters;
mod chat_events;
mod chat_invite_link;
mod chat_invite_link_info;
mod chat_member;
mod chat_member_status;
mod chat_member_status_creator;
mod chat_member_status_administrator;
mod chat_member_status_member;
mod chat_member_status_restricted;
mod chat_member_status_left;
mod chat_member_status_banned;
mod chat_members;
mod chat_members_filter;
mod chat_members_filter_administrators;
mod chat_members_filter_members;
mod chat_members_filter_restricted;
mod chat_members_filter_banned;
mod chat_members_filter_bots;
mod chat_notification_settings;
mod chat_photo;
mod chat_report_reason;
mod chat_report_reason_spam;
mod chat_report_reason_violence;
mod chat_report_reason_pornography;
mod chat_report_reason_child_abuse;
mod chat_report_reason_copyright;
mod chat_report_reason_custom;
mod chat_report_spam_state;
mod chat_type;
mod chat_type_private;
mod chat_type_basic_group;
mod chat_type_supergroup;
mod chat_type_secret;
mod chats;
mod check_chat_username_result;
mod check_chat_username_result_ok;
mod check_chat_username_result_username_invalid;
mod check_chat_username_result_username_occupied;
mod check_chat_username_result_public_chats_too_much;
mod check_chat_username_result_public_groups_unavailable;
mod connected_website;
mod connected_websites;
mod connection_state;
mod connection_state_waiting_for_network;
mod connection_state_connecting_to_proxy;
mod connection_state_connecting;
mod connection_state_updating;
mod connection_state_ready;
mod contact;
mod count;
mod custom_request_result;
mod database_statistics;
mod date;
mod dated_file;
mod deep_link_info;
mod device_token;
mod device_token_firebase_cloud_messaging;
mod device_token_apple_push;
mod device_token_apple_push_vo_i_p;
mod device_token_windows_push;
mod device_token_microsoft_push;
mod device_token_microsoft_push_vo_i_p;
mod device_token_web_push;
mod device_token_simple_push;
mod device_token_ubuntu_push;
mod device_token_black_berry_push;
mod device_token_tizen_push;
mod document;
mod draft_message;
mod email_address_authentication_code_info;
mod encrypted_credentials;
mod encrypted_passport_element;
mod error;
mod file;
mod file_part;
mod file_type;
mod file_type_none;
mod file_type_animation;
mod file_type_audio;
mod file_type_document;
mod file_type_photo;
mod file_type_profile_photo;
mod file_type_secret;
mod file_type_secret_thumbnail;
mod file_type_secure;
mod file_type_sticker;
mod file_type_thumbnail;
mod file_type_unknown;
mod file_type_video;
mod file_type_video_note;
mod file_type_voice_note;
mod file_type_wallpaper;
mod formatted_text;
mod found_messages;
mod game;
mod game_high_score;
mod game_high_scores;
mod hashtags;
mod http_url;
mod identity_document;
mod imported_contacts;
mod inline_keyboard_button;
mod inline_keyboard_button_type;
mod inline_keyboard_button_type_url;
mod inline_keyboard_button_type_callback;
mod inline_keyboard_button_type_callback_game;
mod inline_keyboard_button_type_switch_inline;
mod inline_keyboard_button_type_buy;
mod inline_query_result;
mod inline_query_result_article;
mod inline_query_result_contact;
mod inline_query_result_location;
mod inline_query_result_venue;
mod inline_query_result_game;
mod inline_query_result_animation;
mod inline_query_result_audio;
mod inline_query_result_document;
mod inline_query_result_photo;
mod inline_query_result_sticker;
mod inline_query_result_video;
mod inline_query_result_voice_note;
mod inline_query_results;
mod input_credentials;
mod input_credentials_saved;
mod input_credentials_new;
mod input_credentials_android_pay;
mod input_credentials_apple_pay;
mod input_file;
mod input_file_id;
mod input_file_remote;
mod input_file_local;
mod input_file_generated;
mod input_identity_document;
mod input_inline_query_result;
mod input_inline_query_result_animated_gif;
mod input_inline_query_result_animated_mpeg4;
mod input_inline_query_result_article;
mod input_inline_query_result_audio;
mod input_inline_query_result_contact;
mod input_inline_query_result_document;
mod input_inline_query_result_game;
mod input_inline_query_result_location;
mod input_inline_query_result_photo;
mod input_inline_query_result_sticker;
mod input_inline_query_result_venue;
mod input_inline_query_result_video;
mod input_inline_query_result_voice_note;
mod input_message_content;
mod input_message_text;
mod input_message_animation;
mod input_message_audio;
mod input_message_document;
mod input_message_photo;
mod input_message_sticker;
mod input_message_video;
mod input_message_video_note;
mod input_message_voice_note;
mod input_message_location;
mod input_message_venue;
mod input_message_contact;
mod input_message_game;
mod input_message_invoice;
mod input_message_poll;
mod input_message_forwarded;
mod input_passport_element;
mod input_passport_element_personal_details;
mod input_passport_element_passport;
mod input_passport_element_driver_license;
mod input_passport_element_identity_card;
mod input_passport_element_internal_passport;
mod input_passport_element_address;
mod input_passport_element_utility_bill;
mod input_passport_element_bank_statement;
mod input_passport_element_rental_agreement;
mod input_passport_element_passport_registration;
mod input_passport_element_temporary_registration;
mod input_passport_element_phone_number;
mod input_passport_element_email_address;
mod input_passport_element_error;
mod input_passport_element_error_source;
mod input_passport_element_error_source_unspecified;
mod input_passport_element_error_source_data_field;
mod input_passport_element_error_source_front_side;
mod input_passport_element_error_source_reverse_side;
mod input_passport_element_error_source_selfie;
mod input_passport_element_error_source_translation_file;
mod input_passport_element_error_source_translation_files;
mod input_passport_element_error_source_file;
mod input_passport_element_error_source_files;
mod input_personal_document;
mod input_sticker;
mod input_thumbnail;
mod invoice;
mod keyboard_button;
mod keyboard_button_type;
mod keyboard_button_type_text;
mod keyboard_button_type_request_phone_number;
mod keyboard_button_type_request_location;
mod labeled_price_part;
mod language_pack_info;
mod language_pack_string;
mod language_pack_string_value;
mod language_pack_string_value_ordinary;
mod language_pack_string_value_pluralized;
mod language_pack_string_value_deleted;
mod language_pack_strings;
mod link_state;
mod link_state_none;
mod link_state_knows_phone_number;
mod link_state_is_contact;
mod local_file;
mod localization_target_info;
mod location;
mod log_stream;
mod log_stream_default;
mod log_stream_file;
mod log_stream_empty;
mod log_tags;
mod log_verbosity_level;
mod mask_point;
mod mask_point_forehead;
mod mask_point_eyes;
mod mask_point_mouth;
mod mask_point_chin;
mod mask_position;
mod message;
mod message_content;
mod message_text;
mod message_animation;
mod message_audio;
mod message_document;
mod message_photo;
mod message_expired_photo;
mod message_sticker;
mod message_video;
mod message_expired_video;
mod message_video_note;
mod message_voice_note;
mod message_location;
mod message_venue;
mod message_contact;
mod message_game;
mod message_poll;
mod message_invoice;
mod message_call;
mod message_basic_group_chat_create;
mod message_supergroup_chat_create;
mod message_chat_change_title;
mod message_chat_change_photo;
mod message_chat_delete_photo;
mod message_chat_add_members;
mod message_chat_join_by_link;
mod message_chat_delete_member;
mod message_chat_upgrade_to;
mod message_chat_upgrade_from;
mod message_pin_message;
mod message_screenshot_taken;
mod message_chat_set_ttl;
mod message_custom_service_action;
mod message_game_score;
mod message_payment_successful;
mod message_payment_successful_bot;
mod message_contact_registered;
mod message_website_connected;
mod message_passport_data_sent;
mod message_passport_data_received;
mod message_unsupported;
mod message_forward_info;
mod message_forward_origin;
mod message_forward_origin_user;
mod message_forward_origin_hidden_user;
mod message_forward_origin_channel;
mod message_sending_state;
mod message_sending_state_pending;
mod message_sending_state_failed;
mod messages;
mod network_statistics;
mod network_statistics_entry;
mod network_statistics_entry_file;
mod network_statistics_entry_call;
mod network_type;
mod network_type_none;
mod network_type_mobile;
mod network_type_mobile_roaming;
mod network_type_wi_fi;
mod network_type_other;
mod notification;
mod notification_group;
mod notification_group_type;
mod notification_group_type_messages;
mod notification_group_type_mentions;
mod notification_group_type_secret_chat;
mod notification_group_type_calls;
mod notification_settings_scope;
mod notification_settings_scope_private_chats;
mod notification_settings_scope_group_chats;
mod notification_settings_scope_channel_chats;
mod notification_type;
mod notification_type_new_message;
mod notification_type_new_secret_chat;
mod notification_type_new_call;
mod notification_type_new_push_message;
mod ok;
mod option_value;
mod option_value_boolean;
mod option_value_empty;
mod option_value_integer;
mod option_value_string;
mod order_info;
mod page_block;
mod page_block_title;
mod page_block_subtitle;
mod page_block_author_date;
mod page_block_header;
mod page_block_subheader;
mod page_block_kicker;
mod page_block_paragraph;
mod page_block_preformatted;
mod page_block_footer;
mod page_block_divider;
mod page_block_anchor;
mod page_block_list;
mod page_block_block_quote;
mod page_block_pull_quote;
mod page_block_animation;
mod page_block_audio;
mod page_block_photo;
mod page_block_video;
mod page_block_cover;
mod page_block_embedded;
mod page_block_embedded_post;
mod page_block_collage;
mod page_block_slideshow;
mod page_block_chat_link;
mod page_block_table;
mod page_block_details;
mod page_block_related_articles;
mod page_block_map;
mod page_block_caption;
mod page_block_horizontal_alignment;
mod page_block_horizontal_alignment_left;
mod page_block_horizontal_alignment_center;
mod page_block_horizontal_alignment_right;
mod page_block_list_item;
mod page_block_related_article;
mod page_block_table_cell;
mod page_block_vertical_alignment;
mod page_block_vertical_alignment_top;
mod page_block_vertical_alignment_middle;
mod page_block_vertical_alignment_bottom;
mod passport_authorization_form;
mod passport_element;
mod passport_element_personal_details;
mod passport_element_passport;
mod passport_element_driver_license;
mod passport_element_identity_card;
mod passport_element_internal_passport;
mod passport_element_address;
mod passport_element_utility_bill;
mod passport_element_bank_statement;
mod passport_element_rental_agreement;
mod passport_element_passport_registration;
mod passport_element_temporary_registration;
mod passport_element_phone_number;
mod passport_element_email_address;
mod passport_element_error;
mod passport_element_error_source;
mod passport_element_error_source_unspecified;
mod passport_element_error_source_data_field;
mod passport_element_error_source_front_side;
mod passport_element_error_source_reverse_side;
mod passport_element_error_source_selfie;
mod passport_element_error_source_translation_file;
mod passport_element_error_source_translation_files;
mod passport_element_error_source_file;
mod passport_element_error_source_files;
mod passport_element_type;
mod passport_element_type_personal_details;
mod passport_element_type_passport;
mod passport_element_type_driver_license;
mod passport_element_type_identity_card;
mod passport_element_type_internal_passport;
mod passport_element_type_address;
mod passport_element_type_utility_bill;
mod passport_element_type_bank_statement;
mod passport_element_type_rental_agreement;
mod passport_element_type_passport_registration;
mod passport_element_type_temporary_registration;
mod passport_element_type_phone_number;
mod passport_element_type_email_address;
mod passport_elements;
mod passport_elements_with_errors;
mod passport_required_element;
mod passport_suitable_element;
mod password_state;
mod payment_form;
mod payment_receipt;
mod payment_result;
mod payments_provider_stripe;
mod personal_details;
mod personal_document;
mod photo;
mod photo_size;
mod poll;
mod poll_option;
mod profile_photo;
mod proxies;
mod proxy;
mod proxy_type;
mod proxy_type_socks5;
mod proxy_type_http;
mod proxy_type_mtproto;
mod public_message_link;
mod push_message_content;
mod push_message_content_hidden;
mod push_message_content_animation;
mod push_message_content_audio;
mod push_message_content_contact;
mod push_message_content_contact_registered;
mod push_message_content_document;
mod push_message_content_game;
mod push_message_content_game_score;
mod push_message_content_invoice;
mod push_message_content_location;
mod push_message_content_photo;
mod push_message_content_poll;
mod push_message_content_screenshot_taken;
mod push_message_content_sticker;
mod push_message_content_text;
mod push_message_content_video;
mod push_message_content_video_note;
mod push_message_content_voice_note;
mod push_message_content_basic_group_chat_create;
mod push_message_content_chat_add_members;
mod push_message_content_chat_change_photo;
mod push_message_content_chat_change_title;
mod push_message_content_chat_delete_member;
mod push_message_content_chat_join_by_link;
mod push_message_content_message_forwards;
mod push_message_content_media_album;
mod push_receiver_id;
mod recovery_email_address;
mod remote_file;
mod reply_markup;
mod reply_markup_remove_keyboard;
mod reply_markup_force_reply;
mod reply_markup_show_keyboard;
mod reply_markup_inline_keyboard;
mod rich_text;
mod rich_text_plain;
mod rich_text_bold;
mod rich_text_italic;
mod rich_text_underline;
mod rich_text_strikethrough;
mod rich_text_fixed;
mod rich_text_url;
mod rich_text_email_address;
mod rich_text_subscript;
mod rich_text_superscript;
mod rich_text_marked;
mod rich_text_phone_number;
mod rich_text_icon;
mod rich_text_anchor;
mod rich_texts;
mod saved_credentials;
mod scope_notification_settings;
mod search_messages_filter;
mod search_messages_filter_empty;
mod search_messages_filter_animation;
mod search_messages_filter_audio;
mod search_messages_filter_document;
mod search_messages_filter_photo;
mod search_messages_filter_video;
mod search_messages_filter_voice_note;
mod search_messages_filter_photo_and_video;
mod search_messages_filter_url;
mod search_messages_filter_chat_photo;
mod search_messages_filter_call;
mod search_messages_filter_missed_call;
mod search_messages_filter_video_note;
mod search_messages_filter_voice_and_video_note;
mod search_messages_filter_mention;
mod search_messages_filter_unread_mention;
mod seconds;
mod secret_chat;
mod secret_chat_state;
mod secret_chat_state_pending;
mod secret_chat_state_ready;
mod secret_chat_state_closed;
mod session;
mod sessions;
mod shipping_option;
mod sticker;
mod sticker_emojis;
mod sticker_set;
mod sticker_set_info;
mod sticker_sets;
mod stickers;
mod storage_statistics;
mod storage_statistics_by_chat;
mod storage_statistics_by_file_type;
mod storage_statistics_fast;
mod supergroup;
mod supergroup_full_info;
mod supergroup_members_filter;
mod supergroup_members_filter_recent;
mod supergroup_members_filter_administrators;
mod supergroup_members_filter_search;
mod supergroup_members_filter_restricted;
mod supergroup_members_filter_banned;
mod supergroup_members_filter_bots;
mod t_me_url;
mod t_me_url_type;
mod t_me_url_type_user;
mod t_me_url_type_supergroup;
mod t_me_url_type_chat_invite;
mod t_me_url_type_sticker_set;
mod t_me_urls;
mod tdlib_parameters;
mod temporary_password_state;
mod terms_of_service;
mod test_bytes;
mod test_int;
mod test_string;
mod test_vector_int;
mod test_vector_int_object;
mod test_vector_string;
mod test_vector_string_object;
mod text;
mod text_entities;
mod text_entity;
mod text_entity_type;
mod text_entity_type_mention;
mod text_entity_type_hashtag;
mod text_entity_type_cashtag;
mod text_entity_type_bot_command;
mod text_entity_type_url;
mod text_entity_type_email_address;
mod text_entity_type_bold;
mod text_entity_type_italic;
mod text_entity_type_code;
mod text_entity_type_pre;
mod text_entity_type_pre_code;
mod text_entity_type_text_url;
mod text_entity_type_mention_name;
mod text_entity_type_phone_number;
mod text_parse_mode;
mod text_parse_mode_markdown;
mod text_parse_mode_h_t_m_l;
mod top_chat_category;
mod top_chat_category_users;
mod top_chat_category_bots;
mod top_chat_category_groups;
mod top_chat_category_channels;
mod top_chat_category_inline_bots;
mod top_chat_category_calls;
mod update;
mod update_authorization_state;
mod update_new_message;
mod update_message_send_acknowledged;
mod update_message_send_succeeded;
mod update_message_send_failed;
mod update_message_content;
mod update_message_edited;
mod update_message_views;
mod update_message_content_opened;
mod update_message_mention_read;
mod update_new_chat;
mod update_chat_title;
mod update_chat_photo;
mod update_chat_last_message;
mod update_chat_order;
mod update_chat_is_pinned;
mod update_chat_is_marked_as_unread;
mod update_chat_is_sponsored;
mod update_chat_default_disable_notification;
mod update_chat_read_inbox;
mod update_chat_read_outbox;
mod update_chat_unread_mention_count;
mod update_chat_notification_settings;
mod update_scope_notification_settings;
mod update_chat_pinned_message;
mod update_chat_reply_markup;
mod update_chat_draft_message;
mod update_chat_online_member_count;
mod update_notification;
mod update_notification_group;
mod update_active_notifications;
mod update_have_pending_notifications;
mod update_delete_messages;
mod update_user_chat_action;
mod update_user_status;
mod update_user;
mod update_basic_group;
mod update_supergroup;
mod update_secret_chat;
mod update_user_full_info;
mod update_basic_group_full_info;
mod update_supergroup_full_info;
mod update_service_notification;
mod update_file;
mod update_file_generation_start;
mod update_file_generation_stop;
mod update_call;
mod update_user_privacy_setting_rules;
mod update_unread_message_count;
mod update_unread_chat_count;
mod update_option;
mod update_installed_sticker_sets;
mod update_trending_sticker_sets;
mod update_recent_stickers;
mod update_favorite_stickers;
mod update_saved_animations;
mod update_language_pack_strings;
mod update_connection_state;
mod update_terms_of_service;
mod update_new_inline_query;
mod update_new_chosen_inline_result;
mod update_new_callback_query;
mod update_new_inline_callback_query;
mod update_new_shipping_query;
mod update_new_pre_checkout_query;
mod update_new_custom_event;
mod update_new_custom_query;
mod update_poll;
mod updates;
mod user;
mod user_full_info;
mod user_privacy_setting;
mod user_privacy_setting_show_status;
mod user_privacy_setting_allow_chat_invites;
mod user_privacy_setting_allow_calls;
mod user_privacy_setting_allow_peer_to_peer_calls;
mod user_privacy_setting_rule;
mod user_privacy_setting_rule_allow_all;
mod user_privacy_setting_rule_allow_contacts;
mod user_privacy_setting_rule_allow_users;
mod user_privacy_setting_rule_restrict_all;
mod user_privacy_setting_rule_restrict_contacts;
mod user_privacy_setting_rule_restrict_users;
mod user_privacy_setting_rules;
mod user_profile_photo;
mod user_profile_photos;
mod user_status;
mod user_status_empty;
mod user_status_online;
mod user_status_offline;
mod user_status_recently;
mod user_status_last_week;
mod user_status_last_month;
mod user_type;
mod user_type_regular;
mod user_type_deleted;
mod user_type_bot;
mod user_type_unknown;
mod users;
mod validated_order_info;
mod venue;
mod video;
mod video_note;
mod voice_note;
mod wallpaper;
mod wallpapers;
mod web_page;
mod web_page_instant_view;
mod accept_call;
mod accept_terms_of_service;
mod add_chat_member;
mod add_chat_members;
mod add_custom_server_language_pack;
mod add_favorite_sticker;
mod add_local_message;
mod add_log_message;
mod add_network_statistics;
mod add_proxy;
mod add_recent_sticker;
mod add_recently_found_chat;
mod add_saved_animation;
mod add_sticker_to_set;
mod answer_callback_query;
mod answer_custom_query;
mod answer_inline_query;
mod answer_pre_checkout_query;
mod answer_shipping_query;
mod block_user;
mod cancel_download_file;
mod cancel_upload_file;
mod change_chat_report_spam_state;
mod change_imported_contacts;
mod change_phone_number;
mod change_sticker_set;
mod check_authentication_bot_token;
mod check_authentication_code;
mod check_authentication_password;
mod check_change_phone_number_code;
mod check_chat_invite_link;
mod check_chat_username;
mod check_database_encryption_key;
mod check_email_address_verification_code;
mod check_phone_number_confirmation_code;
mod check_phone_number_verification_code;
mod check_recovery_email_address_code;
mod clean_file_name;
mod clear_all_draft_messages;
mod clear_imported_contacts;
mod clear_recent_stickers;
mod clear_recently_found_chats;
mod close;
mod close_chat;
mod close_secret_chat;
mod create_basic_group_chat;
mod create_call;
mod create_new_basic_group_chat;
mod create_new_secret_chat;
mod create_new_sticker_set;
mod create_new_supergroup_chat;
mod create_private_chat;
mod create_secret_chat;
mod create_supergroup_chat;
mod create_temporary_password;
mod delete_account;
mod delete_chat_history;
mod delete_chat_messages_from_user;
mod delete_chat_reply_markup;
mod delete_file;
mod delete_language_pack;
mod delete_messages;
mod delete_passport_element;
mod delete_profile_photo;
mod delete_saved_credentials;
mod delete_saved_order_info;
mod delete_supergroup;
mod destroy;
mod disable_proxy;
mod discard_call;
mod disconnect_all_websites;
mod disconnect_website;
mod download_file;
mod edit_custom_language_pack_info;
mod edit_inline_message_caption;
mod edit_inline_message_live_location;
mod edit_inline_message_media;
mod edit_inline_message_reply_markup;
mod edit_inline_message_text;
mod edit_message_caption;
mod edit_message_live_location;
mod edit_message_media;
mod edit_message_reply_markup;
mod edit_message_text;
mod edit_proxy;
mod enable_proxy;
mod finish_file_generation;
mod forward_messages;
mod generate_chat_invite_link;
mod get_account_ttl;
mod get_active_live_location_messages;
mod get_active_sessions;
mod get_all_passport_elements;
mod get_application_config;
mod get_archived_sticker_sets;
mod get_attached_sticker_sets;
mod get_authorization_state;
mod get_basic_group;
mod get_basic_group_full_info;
mod get_blocked_users;
mod get_callback_query_answer;
mod get_chat;
mod get_chat_administrators;
mod get_chat_event_log;
mod get_chat_history;
mod get_chat_member;
mod get_chat_message_by_date;
mod get_chat_message_count;
mod get_chat_notification_settings_exceptions;
mod get_chat_pinned_message;
mod get_chat_report_spam_state;
mod get_chat_statistics_url;
mod get_chats;
mod get_connected_websites;
mod get_contacts;
mod get_country_code;
mod get_created_public_chats;
mod get_current_state;
mod get_database_statistics;
mod get_deep_link_info;
mod get_favorite_stickers;
mod get_file;
mod get_file_downloaded_prefix_size;
mod get_file_extension;
mod get_file_mime_type;
mod get_game_high_scores;
mod get_groups_in_common;
mod get_imported_contact_count;
mod get_inline_game_high_scores;
mod get_inline_query_results;
mod get_installed_sticker_sets;
mod get_invite_text;
mod get_language_pack_info;
mod get_language_pack_string;
mod get_language_pack_strings;
mod get_localization_target_info;
mod get_log_stream;
mod get_log_tag_verbosity_level;
mod get_log_tags;
mod get_log_verbosity_level;
mod get_map_thumbnail_file;
mod get_me;
mod get_message;
mod get_message_link;
mod get_message_locally;
mod get_messages;
mod get_network_statistics;
mod get_option;
mod get_passport_authorization_form;
mod get_passport_authorization_form_available_elements;
mod get_passport_element;
mod get_password_state;
mod get_payment_form;
mod get_payment_receipt;
mod get_preferred_country_language;
mod get_proxies;
mod get_proxy_link;
mod get_public_message_link;
mod get_push_receiver_id;
mod get_recent_inline_bots;
mod get_recent_stickers;
mod get_recently_visited_t_me_urls;
mod get_recovery_email_address;
mod get_remote_file;
mod get_replied_message;
mod get_saved_animations;
mod get_saved_order_info;
mod get_scope_notification_settings;
mod get_secret_chat;
mod get_sticker_emojis;
mod get_sticker_set;
mod get_stickers;
mod get_storage_statistics;
mod get_storage_statistics_fast;
mod get_supergroup;
mod get_supergroup_full_info;
mod get_supergroup_members;
mod get_support_user;
mod get_temporary_password_state;
mod get_text_entities;
mod get_top_chats;
mod get_trending_sticker_sets;
mod get_user;
mod get_user_full_info;
mod get_user_privacy_setting_rules;
mod get_user_profile_photos;
mod get_wallpapers;
mod get_web_page_instant_view;
mod get_web_page_preview;
mod import_contacts;
mod join_chat;
mod join_chat_by_invite_link;
mod leave_chat;
mod log_out;
mod open_chat;
mod open_message_content;
mod optimize_storage;
mod parse_text_entities;
mod pin_chat_message;
mod ping_proxy;
mod process_push_notification;
mod read_all_chat_mentions;
mod read_file_part;
mod recover_authentication_password;
mod recover_password;
mod register_device;
mod remove_contacts;
mod remove_favorite_sticker;
mod remove_notification;
mod remove_notification_group;
mod remove_proxy;
mod remove_recent_hashtag;
mod remove_recent_sticker;
mod remove_recently_found_chat;
mod remove_saved_animation;
mod remove_sticker_from_set;
mod remove_top_chat;
mod reorder_installed_sticker_sets;
mod report_chat;
mod report_supergroup_spam;
mod request_authentication_password_recovery;
mod request_password_recovery;
mod resend_authentication_code;
mod resend_change_phone_number_code;
mod resend_email_address_verification_code;
mod resend_phone_number_confirmation_code;
mod resend_phone_number_verification_code;
mod resend_recovery_email_address_code;
mod reset_all_notification_settings;
mod reset_network_statistics;
mod search_call_messages;
mod search_chat_members;
mod search_chat_messages;
mod search_chat_recent_location_messages;
mod search_chats;
mod search_chats_on_server;
mod search_contacts;
mod search_hashtags;
mod search_installed_sticker_sets;
mod search_messages;
mod search_public_chat;
mod search_public_chats;
mod search_secret_messages;
mod search_sticker_set;
mod search_sticker_sets;
mod search_stickers;
mod send_bot_start_message;
mod send_call_debug_information;
mod send_call_rating;
mod send_chat_action;
mod send_chat_screenshot_taken_notification;
mod send_chat_set_ttl_message;
mod send_custom_request;
mod send_email_address_verification_code;
mod send_inline_query_result_message;
mod send_message;
mod send_message_album;
mod send_passport_authorization_form;
mod send_payment_form;
mod send_phone_number_confirmation_code;
mod send_phone_number_verification_code;
mod set_account_ttl;
mod set_alarm;
mod set_authentication_phone_number;
mod set_bio;
mod set_bot_updates_status;
mod set_chat_client_data;
mod set_chat_draft_message;
mod set_chat_member_status;
mod set_chat_notification_settings;
mod set_chat_photo;
mod set_chat_title;
mod set_custom_language_pack;
mod set_custom_language_pack_string;
mod set_database_encryption_key;
mod set_file_generation_progress;
mod set_game_score;
mod set_inline_game_score;
mod set_log_stream;
mod set_log_tag_verbosity_level;
mod set_log_verbosity_level;
mod set_name;
mod set_network_type;
mod set_option;
mod set_passport_element;
mod set_passport_element_errors;
mod set_password;
mod set_pinned_chats;
mod set_poll_answer;
mod set_profile_photo;
mod set_recovery_email_address;
mod set_scope_notification_settings;
mod set_sticker_position_in_set;
mod set_supergroup_description;
mod set_supergroup_sticker_set;
mod set_supergroup_username;
mod set_tdlib_parameters;
mod set_user_privacy_setting_rules;
mod set_username;
mod stop_poll;
mod synchronize_language_pack;
mod terminate_all_other_sessions;
mod terminate_session;
mod test_call_bytes;
mod test_call_empty;
mod test_call_string;
mod test_call_vector_int;
mod test_call_vector_int_object;
mod test_call_vector_string;
mod test_call_vector_string_object;
mod test_get_difference;
mod test_network;
mod test_square_int;
mod test_use_error;
mod test_use_update;
mod toggle_basic_group_administrators;
mod toggle_chat_default_disable_notification;
mod toggle_chat_is_marked_as_unread;
mod toggle_chat_is_pinned;
mod toggle_supergroup_invites;
mod toggle_supergroup_is_all_history_available;
mod toggle_supergroup_sign_messages;
mod unblock_user;
mod unpin_chat_message;
mod upgrade_basic_group_chat_to_supergroup_chat;
mod upload_file;
mod upload_sticker_file;
mod validate_order_info;
mod view_messages;
mod view_trending_sticker_sets;
mod write_generated_file_part;
